#!/usr/bin/with-contenv /bin/bash
set -e

##
# Add docker environment variables to /etc/nginx/fastcgi_params
##
sed -i '/#AUTO_ENV_START/,/#AUTO_ENV_END/d' /etc/nginx/fastcgi_params
echo "#AUTO_ENV_START" >> /etc/nginx/fastcgi_params
while IFS='=' read -r name value; do
        echo "fastcgi_param $name '$value';" >> /etc/nginx/fastcgi_params
done < <(env)
echo "#AUTO_ENV_END" >> /etc/nginx/fastcgi_params
