#!/usr/bin/with-contenv /bin/bash
set -e

# Move all docker secrets to s6 env vars
cp /run/secrets/* /run/s6/container_environment/

# Strip new line endings from all secrets
for file in /run/s6/container_environment/*
do
        /bin/echo -n $(cat $file) > $file
done
